//------------------------------------------------------------------------------
// <auto-generated>
// Ecommerce Startup config
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Hosting;

[assembly: HostingStartup(typeof(motovalle.Ecommerce.Areas.Identity.IdentityHostingStartup))]
namespace motovalle.Ecommerce.Areas.Identity
{
    public class IdentityHostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices((context, services) => {
            });
        }
    }
}