// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace Ecommerce.DAL.Migrations
{
    public partial class AddCategoryIdToModels : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "fk_categories_id",
                table: "models",
                type: "int(11)",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "fk_categories_id",
                table: "models",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_models_fk_categories_id",
                table: "models",
                column: "fk_categories_id");

            migrationBuilder.AddForeignKey(
                name: "categories_models",
                table: "models",
                column: "fk_categories_id",
                principalTable: "categories",
                principalColumn: "categories_id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_models_categories_FkCategoryCategoriesId",
                table: "models");

            migrationBuilder.DropIndex(
                name: "IX_models_FkCategoryCategoriesId",
                table: "models");

            migrationBuilder.DropColumn(
                name: "fk_categories_id",
                table: "models");

            migrationBuilder.DropColumn(
                name: "FkCategoryCategoriesId",
                table: "models");
        }
    }
}
