//------------------------------------------------------------------------------
// <auto-generated>
// Ecommerce Startup config
// </auto-generated>
//------------------------------------------------------------------------------

namespace motovalle.Ecommerce
{
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using Microsoft.EntityFrameworkCore;
    using Inventek.CMS.DAL.EF;
    using Inventek.CMS.DAL.Repos.Interfaces;
    using Inventek.CMS.DAL.Repos;
    using global::Ecommerce.DAL.EF;
    using global::Ecommerce.DAL.Repos.Interfaces;
    using global::Ecommerce.DAL.Repos;
    using motovalle.Ecommerce.Models.Entities.Identity.Data;
    using System;
    using motovalle.Ecommerce.Models.Entities.Identity;
    using motovalle.Ecommerce.Helpers.EmailSender;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Newtonsoft.Json.Serialization;
    using Newtonsoft.Json;
    using Microsoft.AspNetCore.Authentication.JwtBearer;
    using Microsoft.IdentityModel.Tokens;
    using System.Text;
    using motovalle.Ecommerce.Helpers.ApiRequest.Services;
    using motovalle.Ecommerce.Helpers.ReportHelper;
    using motovalle.Ecommerce.Helpers.Services;
    using reCAPTCHA.AspNetCore;
    using motovalle.Ecommerce.Helpers.MercadoPagoPayment.Facade;
    using motovalle.Ecommerce.Helpers.MercadoPagoPayment;
    using Inventek.ERP.DAL.EF;
    using System.Net.Http.Headers;
    using motovalle.Ecommerce.Helpers.Services.WompiPaymentGateway;
    using motovalle.Ecommerce.Models;

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        //// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                //// This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.ConsentCookie.Name = "MotovalleCookieConsent";
                options.ConsentCookie.Expiration = TimeSpan.FromDays(360);
            });

            ////Syncfusion stuff
            services.AddMvc()
                .AddNewtonsoftJson(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver())
                .AddNewtonsoftJson(options => options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore)
                .AddNewtonsoftJson(options => options.SerializerSettings.DateFormatHandling = DateFormatHandling.MicrosoftDateFormat)
                .AddNewtonsoftJson(options => options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc);
            ////end sync

            ////JWT Settings
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.RequireHttpsMetadata = false;
                    options.SaveToken = true;
                    options.TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidateIssuer = true,
                        ValidateAudience = true,
                        ValidAudience = Configuration.GetSection("JwtSettings").GetValue<string>("Audience"),
                        ValidIssuer = Configuration.GetSection("JwtSettings").GetValue<string>("Issuer"),
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration.GetSection("JwtSettings").GetValue<string>("Key")))
                    };
                });

            ////Identity settings
            services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
            {
                //// Password settings
                options.Password.RequireDigit = this.Configuration.GetSection("IdentitySettings").GetValue<bool>("RequireDigit");
                options.Password.RequiredLength = this.Configuration.GetSection("IdentitySettings").GetValue<int>("RequiredLength");
                options.Password.RequireNonAlphanumeric = this.Configuration.GetSection("IdentitySettings").GetValue<bool>("RequireNonAlphanumeric");
                options.Password.RequireUppercase = this.Configuration.GetSection("IdentitySettings").GetValue<bool>("RequireUppercase");
                options.Password.RequireLowercase = this.Configuration.GetSection("IdentitySettings").GetValue<bool>("RequireLowercase");

                //// Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(this.Configuration.GetSection("IdentitySettings").GetValue<int>("DefaultLockoutTimeSpan"));
                options.Lockout.MaxFailedAccessAttempts = this.Configuration.GetSection("IdentitySettings").GetValue<int>("MaxFailedAccessAttempts");

                //// User settings
                options.User.RequireUniqueEmail = this.Configuration.GetSection("IdentitySettings").GetValue<bool>("RequireUniqueEmail");

                //// Sing in 
                options.SignIn.RequireConfirmedEmail = this.Configuration.GetSection("IdentitySettings").GetValue<bool>("RequireConfirmedEmail");
            }).AddEntityFrameworkStores<EcommerceAppUsersContext>()
              .AddDefaultTokenProviders();

            ////Configure the app's cookie
            services.ConfigureApplicationCookie(options =>
            {
                options.AccessDeniedPath = "/Identity/Account/AccessDenied";
                options.Cookie.Name = "MotovalleIdentityCookieConsent";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(this.Configuration.GetSection("IdentitySettings").GetValue<int>("ExpireTimeSpan"));
                options.LoginPath = "/Identity/Account/Login";
                options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
                options.SlidingExpiration = true;
            });

            #region Contexts
            ////Context for CMS
            services.AddDbContext<blogContext>(options =>
                options.UseMySql(Configuration.GetConnectionString("CMSConnection")));

            ////Context for Ecommerce
            services.AddDbContext<ecommerceContext>(options =>
                options.UseMySql(this.Configuration.GetConnectionString("DefaultConnection")));

            ////Context for App Users
            services.AddDbContext<EcommerceAppUsersContext>(options =>
                options.UseMySql(this.Configuration.GetConnectionString("UsersConnection")));

            //Context for Custom Pages -> Inventek ERP Code
            services.AddDbContext<inventekContext>(options =>
                options.UseMySql(this.Configuration.GetConnectionString("InventekConnection")));

            // Context for Landing Page
            services.AddDbContext<msi_ecommerceContext>(options => options
                    .UseMySql(Configuration.GetConnectionString("DefaultConnection")));

            // Context for petronas Page
            services.AddDbContext<motovalle_petronasContext>(options => options
                    .UseMySql(Configuration.GetConnectionString("PetronasConnection")));

            // Context for Motovalle Page
            services.AddDbContext<MOTOVALLEContext>(options => options
                    .UseSqlServer(Configuration.GetConnectionString("MotovalleConnection")));
            #endregion

            ////Configure Depedency Injection for our repositories
            #region Repositories
            services.AddScoped<IBodyStylesRepo, BodyStylesRepo>();
            services.AddScoped<ICategoryPicturesRepo, CategoryPicturesRepo>();
            services.AddScoped<ICategoryRepo, CategoryRepo>();
            services.AddScoped<IColorsRepo, ColorsRepo>();
            services.AddScoped<ICustomersRepo, CustomersRepo>();
            services.AddScoped<IDriveTrainsRepo, DriveTrainsRepo>();
            services.AddScoped<IEngineTypesRepo, EngineTypesRepo>();
            services.AddScoped<IEpaClassesRepo, EpaClassesRepo>();
            services.AddScoped<IFundingRequestsRepo, FundingRequestsRepo>();
            services.AddScoped<IInventoryItemsRepo, InventoryItemsRepo>();
            services.AddScoped<IInventoryItemPicturesRepo, InventoryItemPicturesRepo>();
            services.AddScoped<IInterestedCustomersRepo, InterestedCustomersRepo>();
            services.AddScoped<IMakesRepo, MakesRepo>();
            services.AddScoped<IModelsRepo, ModelsRepo>();
            services.AddScoped<INewsletterSubscriptionsRepo, NewsletterSubscriptionsRepo>();
            services.AddScoped<IOrderDetailsRepo, OrderDetailsRepo>();
            services.AddScoped<IOrdersRepo, OrdersRepo>();
            services.AddScoped<IProductsRepo, ProductsRepo>();
            services.AddScoped<IShoppingCartRecordsRepo, ShoppingCartRecordsRepo>();
            services.AddScoped<IShoppingCartRecordsGuestRepo, ShoppingCartRecordsGuestRepo>();
            services.AddScoped<ITransmissionsRepo, TransmissionsRepo>();
            services.AddScoped<IWarrantiesRepo, WarrantiesRepo>();
            services.AddScoped<ITaxesRepo, TaxesRepo>();
            services.AddScoped<ITaxesForInventoryRepo, TaxesForInventoryRepo>();
            services.AddScoped<IHOrdersTaxesRepo, HOrdersTaxesRepo>();
            services.AddScoped<IProductDocumentsCategoriesRepo, ProductDocumentsCategoriesRepo>();
            services.AddScoped<IProductDocumentsRepo, ProductDocumentsRepo>();
            services.AddScoped<IAspirationTypesRepo, AspirationTypesRepo>();
            services.AddScoped<IBladeTypesRepo, BladeTypesRepo>();
            services.AddScoped<IChamberDimensionsRepo, ChamberDimensionsRepo>();
            services.AddScoped<IConditioningSystemsRepo, ConditioningSystemsRepo>();
            services.AddScoped<IConfigurationTypesRepo, ConfigurationTypesRepo>();
            services.AddScoped<IFrontTiresTypesRepo, FrontTiresTypesRepo>();
            services.AddScoped<IHitchPinesRepo, HitchPinesRepo>();
            services.AddScoped<IHitchSystemsRepo, HitchSystemsRepo>();
            services.AddScoped<IRearTiresTypesRepo, RearTiresTypesRepo>();
            services.AddScoped<ISeparationSystemsRepo, SeparationSystemsRepo>();
            services.AddScoped<ITurningRadiusTypesRepo, TurningRadiusTypesRepo>();
            services.AddScoped<ICampaignLeadsRepo, CampaignLeadsRepo>();
            services.AddScoped<ISearchEngineOptimizationsRepo, SearchEngineOptimizationsRepo>();
            services.AddScoped<IHeroImagesRepo, HeroImagesRepo>();
            services.AddScoped<IProductMaintenancesRepo, ProductMaintenancesRepo>();

            services.AddScoped<IBlogRepository, BlogRepository>(); //Dependency Injection for CMS 
            #endregion

            ////Transversal services injected
            services.AddTransient<IEmailSenderExtended, EmailSender>();
            services.AddTransient<IServicesHelper, ServicesHelper>();
            services.AddTransient<IMercadoPagoHelper, MercadoPagoHelper>();
            services.AddScoped<IReportHelper, ReportHelper>();
            services.AddScoped<IGuestUserHelper, GuestUserHelper>();
            services.AddScoped<IWompiPaymentGatewayService, WompiPaymentGatewayService>();
            services.AddTransient<SEOSearchHelper>();

            ////Recaptcha Service
            services.Configure<RecaptchaSettings>(Configuration.GetSection("RecaptchaSettings"));
            services.AddTransient<IRecaptchaService, RecaptchaService>();

            ////Http Clients Services
            services.AddHttpClient("Wompi", x =>
            {
                x.BaseAddress = new Uri(this.Configuration.GetSection("WompiSettings").GetValue<string>("Endpoint"));
                x.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            });

            //services.AddControllersWithViews();
            services.AddControllersWithViews().AddRazorRuntimeCompilation(); // Se agrega RunTimeCompilastions para la actualización de la pagína
            services.AddRazorPages();
            services.AddMvc();
        }

        //// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("MzA0NTQ1QDMxMzgyZTMyMmUzMGdDZ0Y2clVjazF1d0NsMGdJYWVCM21GeG84a1FBb2w5L3NTdWlabDViUXc9");
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseStatusCodePagesWithReExecute("/Error/{0}");

                //// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

                endpoints.MapRazorPages();
            });
        }
    }
}
