//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace motovalle.Ecommerce.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("motovalle.Ecommerce.Resources.StaticResources", typeof(StaticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro &lt;b&gt;creado&lt;/b&gt; correctamente.
        /// </summary>
        public static string CreateOk {
            get {
                return ResourceManager.GetString("CreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro &lt;b&gt;eliminado&lt;/b&gt; correctamente.
        /// </summary>
        public static string DeleteOk {
            get {
                return ResourceManager.GetString("DeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro &lt;b&gt;editado&lt;/b&gt; correctamente.
        /// </summary>
        public static string EditOk {
            get {
                return ResourceManager.GetString("EditOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot; margin-top: 0px; margin-bottom: 1rem; font-size: 14px; color: rgb(0, 36, 73); font-family: &amp;quot;SF UI Display&amp;quot;; font-style: normal; font-weight: 400; text-align: left; text-indent: 0px; white-space: normal; background-color: rgb(255, 255, 255);&quot;&gt;A través de éste, Usted como cliente o prospecto de cliente, acuerda las condiciones sobre el uso de una firma electrónica por su parte, la cual le permitirá identificarlo personalmente, así como aceptar y reconocer el contenido de los documentos o  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ElectronicSignatureAgreement {
            get {
                return ResourceManager.GetString("ElectronicSignatureAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios no disponibles. Por favor intente nuevamente..
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el rango máximo de precios.
        /// </summary>
        public static string RangeMaxValidation {
            get {
                return ResourceManager.GetString("RangeMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el rango mínimo de precios.
        /// </summary>
        public static string RangeMinValidation {
            get {
                return ResourceManager.GetString("RangeMinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot; margin-top: 0px; margin-bottom: 1rem; font-size: 14px; color: rgb(0, 36, 73); font-family: &amp;quot;SF UI Display&amp;quot;; font-style: normal; font-weight: 400; text-align: left; text-indent: 0px; white-space: normal; background-color: rgb(255, 255, 255);&quot;&gt;De acuerdo con lo establecido por la ley y sus reglamentos, la Superintendencia Financiera de Colombia y demás autoridades pertinentes, declaro que:&lt;/p&gt;&lt;ol style=&quot; margin-top: 0px; margin-bottom: 1rem; color: rgb(0, 36, 73); font-family: &amp;quot;SF UI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RiskCenterAgreement {
            get {
                return ResourceManager.GetString("RiskCenterAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de vehículo.
        /// </summary>
        public static string VehicleTypeValidation {
            get {
                return ResourceManager.GetString("VehicleTypeValidation", resourceCulture);
            }
        }
    }
}
